# Generated by Django 4.0.5 on 2023-03-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0006_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('service', 'car_class'), 'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterField(
            model_name='callapplication',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='callapplication',
            name='msg',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='callapplication',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='callapplication',
            name='phone_number',
            field=models.CharField(max_length=16, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
