# Generated by Django 4.0.5 on 2023-04-01 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TireStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(blank=True, choices=[('Создан', 'Создан'), ('Отменён', 'Отменён'), ('На хранении', 'На хранении'), ('Завершён', 'Завершён'), ('Передан в работу', 'Передан в работу'), ('Готов к получению', 'Готов к получению')], default='Ожидает подтверждения', max_length=30, verbose_name='Статус')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.periodofstorage', verbose_name='Период хранение')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.quantityoftires', verbose_name='Количество')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.tiresize', verbose_name='Размер шин')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
        ),
    ]
