# Generated by Django 4.0.5 on 2023-04-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstorage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderstorage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
