# Generated by Django 4.0.5 on 2023-04-04 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstorage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 18, 20, 53, 531465, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='orderstorage',
            name='payed_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 18, 20, 53, 531465, tzinfo=utc), null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='orderstorage',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 18, 20, 53, 531465, tzinfo=utc), verbose_name='Обновлено'),
        ),
    ]
