# Generated by Django 4.0.5 on 2023-04-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tirestore',
            old_name='client',
            new_name='user',
        ),
    ]
