# Generated by Django 4.0.5 on 2023-04-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_orderstorage_adress_alter_orderstorage_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstorage',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='orderstorage',
            name='adress',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Адрес сервиса'),
        ),
        migrations.AlterField(
            model_name='orderstorage',
            name='period',
            field=models.IntegerField(blank=True, null=True, verbose_name='Период хранение'),
        ),
        migrations.AlterField(
            model_name='orderstorage',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Размер шин'),
        ),
    ]
