# Generated by Django 4.0.5 on 2023-04-13 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0003_remove_orderstorage_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstorage',
            name='adress',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='orderstorage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='orderstorage',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='Is Payded?'),
        ),
        migrations.AlterField(
            model_name='orderstorage',
            name='payed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payded_at'),
        ),
        migrations.AlterField(
            model_name='orderstorage',
            name='period',
            field=models.IntegerField(blank=True, null=True, verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='orderstorage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orderstorage',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='orderstorage',
            name='status',
            field=models.IntegerField(choices=[(0, 'Create'), (1, 'IN_Storage'), (2, 'Cancel'), (3, 'Finish')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orderstorage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='orderstorage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
