# Generated by Django 4.0.5 on 2023-04-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_remove_orderstorage_status_orderstorage_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstorage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
    ]
