# Generated by Django 4.0.5 on 2023-04-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_orderstorage_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstorage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Price'),
        ),
    ]
