# Generated by Django 4.0.5 on 2023-04-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_orderstorage_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstorage',
            name='status',
            field=models.IntegerField(choices=[(0, 'Create'), (1, 'IN_Storage'), (2, 'Cancel'), (3, 'Finish')], default=0, verbose_name='Status'),
        ),
    ]
