# Generated by Django 4.0.5 on 2023-04-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_orderstorage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstorage',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
    ]
