# Generated by Django 4.0.5 on 2023-04-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_alter_orderstorage_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstorage',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Price'),
        ),
    ]
