# Generated by Django 4.0.5 on 2023-04-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_alter_orderstorage_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstorage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='orderstorage',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
        migrations.AlterField(
            model_name='orderstorage',
            name='payed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='orderstorage',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderstorage',
            name='status',
            field=models.IntegerField(choices=[(0, 'Создан'), (1, 'На хранении'), (2, 'Отменён'), (3, 'Завершен')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderstorage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
    ]
